apiVersion: v1
kind: Service
metadata:
  name: staging-geovany-welch-chouette-frontend-service
  namespace: staging-geovany-welch-chouette-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: staging-geovany-welch-chouette-frontend
