apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-geovany-welch-chouette-frontend-cert
  namespace: prod-geovany-welch-chouette-frontend
spec:
  secretName: prod-geovany-welch-chouette-frontend-tls
  dnsNames:
    - chouette.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
