apiVersion: v1
kind: Service
metadata:
  name: prod-geovany-welch-chouette-frontend-service
  namespace: prod-geovany-welch-chouette-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: prod-geovany-welch-chouette-frontend
